### ISSUE TITLE
License

### ISSUE THREAD

**Issue by legoktm** [joseignm/GraFa#2]
Hi, I quickly checked, but wasn't able to find any license statement for the code. Could you please add one? <https://www.gnu.org/licenses/license-recommendations.html> might be helpful. Thanks!

**Comment by nicolas-raoul** [comment]
Or public domain, so that it can be reused by as many people as possible (for instance a castles history research group willing to offer on their website a UI letting people search for castles).

**Comment by legoktm** [comment]
I don't see how other free software licenses would prevent that? But either way, if you do want public domain please use CC-0 (<https://creativecommons.org/publicdomain/zero/1.0/>) because the concept of a "public domain" does not exist in all countries.

**Comment by nicolas-raoul** [comment]
@legoktm Very true. But GPL could cause problem with people wanting to merge the code with other code whose license requires attribution. AGPL would prevent people from merging with proprietary software, which is sometimes a good thing (for instance if I create an open source enterprise webapp I would make it AGPL), but in the case of GraFa the goal of this software is to allow people to browse Wikidata, so I can't imagine any bad thing happening with CC0

Since the software is for Wikidata, I would say the very liberal CC0 license present no danger, and it is always the easiest license to integrate, so in this case it is definitely the one I would choose :-)

**Comment by joseignm** [comment]
The code is under Apache License v2
