### ISSUE TITLE
When choosing a value for a property, sort by number of occurrences in the results

### ISSUE THREAD

**Issue by nicolas-raoul** [joseignm/GraFa#4]
For instance from http://grafa.dcc.uchile.cl/search?keyword=Donald when you click on the + for "instance of", it is hard to find "human" in the dropdown list, even though most of the results have this "instance of".

**Comment by joseignm** [comment]
Values are sorted by ranking now. Ranking is prefered over occurrences is most of the cases and it is faster that counting the occurrences.

**Comment by nicolas-raoul** [comment]
Thanks!
Now the highest item in the "instance of" dropdown is "death", the second is "human".
Even though I am sure it could be perfected even further, it is better than before, thanks :-)

**Comment by aidhog** [comment]
Yep, it's tricky, esp. whether to choose frequency or PageRank. For type suggestions (e.g., the instance-of dropdown), we used frequency at the start, but then there are only 200 countries and 3000 third level administrative regions of countries, so we swapped to PageRank and the results became a lot more intuitive. For facet values, it's a trickier one. When you're looking at person, perhaps, and you click on sibling as a facet property, should we prioritise someone like Barack Obama, or someone with a lot of siblings? I guess it depends. :)

In this case PageRank happens to be easier/faster since it does not vary for the current results, so we go with that for now!
